### ISSUE TITLE
The implementation of the generator is CNN rather than MLP

### ISSUE THREAD

**Issue by yihua7** [nintendops/IPFN#1]
Hi, thanks for sharing the code,
In the paper, the generator is a 10-layer MLP with ReLU activations. However, in code implementation [(models/vanilla_mlp.py line 32)](https://github.com/nintendops/IPFN/blob/e41c42fa2d56db5b6aa0538b800dfa2c24eed8f0/models/vanilla_mlp.py#L32), the module netG_mlp_v1 is invoked and it is composed of convolutional layers [(here)](https://github.com/nintendops/IPFN/blob/e41c42fa2d56db5b6aa0538b800dfa2c24eed8f0/core/network_blocks.py#L43). The code and paper are contradictory here. 
Which one should we choose to achieve the SOTA performance as shown in the paper?

**Comment by yihua7** [comment]
There are some small errors in the code:
The [line 58](https://github.com/nintendops/IPFN/blob/e41c42fa2d56db5b6aa0538b800dfa2c24eed8f0/core/core_layers.py#L58) in core_layers.py should be changed to `self.layer = layer(nf_in, nf_out, kernel_size, stride, padding, bias=bias, padding_mode=padding_mode)` because the 6th argument is dilation. The same to lines 68 and 73.

**Comment by nintendops** [comment]
> Hi, thanks for sharing the code, In the paper, the generator is a 10-layer MLP with ReLU activations. However, in code implementation [(models/vanilla_mlp.py line 32)](https://github.com/nintendops/IPFN/blob/e41c42fa2d56db5b6aa0538b800dfa2c24eed8f0/models/vanilla_mlp.py#L32), the module netG_mlp_v1 is invoked and it is composed of convolutional layers [(here)](https://github.com/nintendops/IPFN/blob/e41c42fa2d56db5b6aa0538b800dfa2c24eed8f0/core/network_blocks.py#L43). The code and paper are contradictory here. Which one should we choose to achieve the SOTA performance as shown in the paper?

Hi yihua, thanks for pointing out the small errors! This will be fixed in the next update. 

To answer your first question: since the mlp attempts to learn a mapping from individual coordinates (aka pixel locations) to features, in practice this can be easily implemented by a 1x1 conv2d whose receptive field is limited to the location itself. This practice can also be found in previous mlp-based generative network (e.g. https://github.com/henzler/neuraltexture)

Please use the netG_mlp_v1 model to reproduce results from the paper. 
I will add a complete readme to the repo in a few days~

**Comment by yihua7** [comment]
Makes sense! Thanks for your answer!
